//  File doc/quickbook/oglplus/quickref/enums/limit_query.hpp
//
//  Automatically generated file, DO NOT modify manually.
//  Edit the source 'source/enums/oglplus/limit_query.txt'
//  or the 'source/enums/make_enum.py' script instead.
//
//  Copyright 2010-2015 Matus Chochlik.
//  Distributed under the Boost Software License, Version 1.0.
//  See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt
//
//[oglplus_enums_limit_query

enum class LimitQuery : GLenum
{
	Max3DTextureSize                           = GL_MAX_3D_TEXTURE_SIZE,
	MaxArrayTextureLayers                      = GL_MAX_ARRAY_TEXTURE_LAYERS,
	MaxAtomicCounterBufferBindings             = GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS,
	MaxAtomicCounterBufferSize                 = GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE,
	MaxClipDistances                           = GL_MAX_CLIP_DISTANCES,
	MaxCullDistances                           = GL_MAX_CULL_DISTANCES,
	MaxCombinedClipAndCullDistances            = GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES,
	MaxColorAttachments                        = GL_MAX_COLOR_ATTACHMENTS,
	MaxColorTextureSamples                     = GL_MAX_COLOR_TEXTURE_SAMPLES,
	MaxCombinedAtomicCounterBuffers            = GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS,
	MaxCombinedAtomicCounters                  = GL_MAX_COMBINED_ATOMIC_COUNTERS,
	MaxCombinedFragmentUniformComponents       = GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
	MaxCombinedGeometryUniformComponents       = GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS,
	MaxCombinedImageUniforms                   = GL_MAX_COMBINED_IMAGE_UNIFORMS,
	MaxCombinedImageUnitsAndFragmentOutputs    = GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS,
	MaxCombinedTessControlUniformComponents    = GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS,
	MaxCombinedTessEvaluationUniformComponents = GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS,
	MaxCombinedTextureImageUnits               = GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS,
	MaxCombinedUniformBlocks                   = GL_MAX_COMBINED_UNIFORM_BLOCKS,
	MaxCombinedVertexUniformComponents         = GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
	MaxCubeMapTextureSize                      = GL_MAX_CUBE_MAP_TEXTURE_SIZE,
	MaxDepthTextureSamples                     = GL_MAX_DEPTH_TEXTURE_SAMPLES,
	MaxDrawBuffers                             = GL_MAX_DRAW_BUFFERS,
	MaxDualSourceDrawBuffers                   = GL_MAX_DUAL_SOURCE_DRAW_BUFFERS,
	MaxElementsIndices                         = GL_MAX_ELEMENTS_INDICES,
	MaxElementsVertices                        = GL_MAX_ELEMENTS_VERTICES,
	MaxFragmentAtomicCounterBuffers            = GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS,
	MaxFragmentAtomicCounters                  = GL_MAX_FRAGMENT_ATOMIC_COUNTERS,
	MaxFragmentImageUniforms                   = GL_MAX_FRAGMENT_IMAGE_UNIFORMS,
	MaxFragmentInputComponents                 = GL_MAX_FRAGMENT_INPUT_COMPONENTS,
	MaxFragmentInterpolationOffset             = GL_MAX_FRAGMENT_INTERPOLATION_OFFSET,
	MaxFragmentUniformBlocks                   = GL_MAX_FRAGMENT_UNIFORM_BLOCKS,
	MaxFragmentUniformComponents               = GL_MAX_FRAGMENT_UNIFORM_COMPONENTS,
	MaxFragmentUniformVectors                  = GL_MAX_FRAGMENT_UNIFORM_VECTORS,
	MaxGeometryAtomicCounterBuffers            = GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS,
	MaxGeometryAtomicCounters                  = GL_MAX_GEOMETRY_ATOMIC_COUNTERS,
	MaxGeometryImageUniforms                   = GL_MAX_GEOMETRY_IMAGE_UNIFORMS,
	MaxGeometryInputComponents                 = GL_MAX_GEOMETRY_INPUT_COMPONENTS,
	MaxGeometryOutputComponents                = GL_MAX_GEOMETRY_OUTPUT_COMPONENTS,
	MaxGeometryOutputVertices                  = GL_MAX_GEOMETRY_OUTPUT_VERTICES,
	MaxGeometryShaderInvocations               = GL_MAX_GEOMETRY_SHADER_INVOCATIONS,
	MaxGeometryTextureImageUnits               = GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS,
	MaxGeometryTotalOutputComponents           = GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS,
	MaxGeometryUniformBlocks                   = GL_MAX_GEOMETRY_UNIFORM_BLOCKS,
	MaxGeometryUniformComponents               = GL_MAX_GEOMETRY_UNIFORM_COMPONENTS,
	MaxImageSamples                            = GL_MAX_IMAGE_SAMPLES,
	MaxImageUnits                              = GL_MAX_IMAGE_UNITS,
	MaxIntegerSamples                          = GL_MAX_INTEGER_SAMPLES,
	MaxPatchVertices                           = GL_MAX_PATCH_VERTICES,
	MaxProgramTexelOffset                      = GL_MAX_PROGRAM_TEXEL_OFFSET,
	MaxProgramTextureGatherOffset              = GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET,
	MaxRectangleTextureSize                    = GL_MAX_RECTANGLE_TEXTURE_SIZE,
	MaxRenderbufferSize                        = GL_MAX_RENDERBUFFER_SIZE,
	MaxSampleMaskWords                         = GL_MAX_SAMPLE_MASK_WORDS,
	MaxSamples                                 = GL_MAX_SAMPLES,
	MaxServerWaitTimeout                       = GL_MAX_SERVER_WAIT_TIMEOUT,
	MaxSubroutines                             = GL_MAX_SUBROUTINES,
	MaxSubroutineUniformLocations              = GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS,
	MaxTessControlAtomicCounterBuffers         = GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS,
	MaxTessControlAtomicCounters               = GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS,
	MaxTessControlImageUniforms                = GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS,
	MaxTessControlInputComponents              = GL_MAX_TESS_CONTROL_INPUT_COMPONENTS,
	MaxTessControlOutputComponents             = GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS,
	MaxTessControlTextureImageUnits            = GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS,
	MaxTessControlTotalOutputComponents        = GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS,
	MaxTessControlUniformBlocks                = GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS,
	MaxTessControlUniformComponents            = GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS,
	MaxTessEvaluationAtomicCounterBuffers      = GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS,
	MaxTessEvaluationAtomicCounters            = GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS,
	MaxTessEvaluationImageUniforms             = GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS,
	MaxTessEvaluationInputComponents           = GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS,
	MaxTessEvaluationOutputComponents          = GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS,
	MaxTessEvaluationTextureImageUnits         = GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS,
	MaxTessEvaluationUniformBlocks             = GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS,
	MaxTessEvaluationUniformComponents         = GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS,
	MaxTessGenLevel                            = GL_MAX_TESS_GEN_LEVEL,
	MaxTessPatchComponents                     = GL_MAX_TESS_PATCH_COMPONENTS,
	MaxTextureBufferSize                       = GL_MAX_TEXTURE_BUFFER_SIZE,
	MaxTextureImageUnits                       = GL_MAX_TEXTURE_IMAGE_UNITS,
	MaxTextureLodBias                          = GL_MAX_TEXTURE_LOD_BIAS,
	MaxTextureSize                             = GL_MAX_TEXTURE_SIZE,
	MaxTransformFeedbackBuffers                = GL_MAX_TRANSFORM_FEEDBACK_BUFFERS,
	MaxTransformFeedbackInterleavedComponents  = GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
	MaxTransformFeedbackSeparateAttribs        = GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,
	MaxTransformFeedbackSeparateComponents     = GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
	MaxUniformBlockSize                        = GL_MAX_UNIFORM_BLOCK_SIZE,
	MaxUniformBufferBindings                   = GL_MAX_UNIFORM_BUFFER_BINDINGS,
	MaxVaryingComponents                       = GL_MAX_VARYING_COMPONENTS,
	MaxVaryingVectors                          = GL_MAX_VARYING_VECTORS,
	MaxVertexAtomicCounterBuffers              = GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS,
	MaxVertexAtomicCounters                    = GL_MAX_VERTEX_ATOMIC_COUNTERS,
	MaxVertexAttribs                           = GL_MAX_VERTEX_ATTRIBS,
	MaxVertexImageUniforms                     = GL_MAX_VERTEX_IMAGE_UNIFORMS,
	MaxVertexOutputComponents                  = GL_MAX_VERTEX_OUTPUT_COMPONENTS,
	MaxVertexStreams                           = GL_MAX_VERTEX_STREAMS,
	MaxVertexTextureImageUnits                 = GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS,
	MaxVertexUniformBlocks                     = GL_MAX_VERTEX_UNIFORM_BLOCKS,
	MaxVertexUniformComponents                 = GL_MAX_VERTEX_UNIFORM_COMPONENTS,
	MaxVertexUniformVectors                    = GL_MAX_VERTEX_UNIFORM_VECTORS,
	MaxViewportDims                            = GL_MAX_VIEWPORT_DIMS,
	MaxViewports                               = GL_MAX_VIEWPORTS,
	MaxComputeWorkGroupCount                   = GL_MAX_COMPUTE_WORK_GROUP_COUNT,
	MaxComputeWorkGroupSize                    = GL_MAX_COMPUTE_WORK_GROUP_SIZE,
	MaxComputeWorkGroupInvocations             = GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS,
	MaxComputeSharedMemorySize                 = GL_MAX_COMPUTE_SHARED_MEMORY_SIZE,
	MinFragmentInterpolationOffset             = GL_MIN_FRAGMENT_INTERPOLATION_OFFSET,
	MinMapBufferAlignment                      = GL_MIN_MAP_BUFFER_ALIGNMENT,
	MinProgramTexelOffset                      = GL_MIN_PROGRAM_TEXEL_OFFSET,
	MinProgramTextureGatherOffset              = GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET
};

template <>
__Range<LimitQuery> __EnumValueRange<LimitQuery>(void);

__StrCRef __EnumValueName(LimitQuery);

//]
